### ISSUE TITLE
Current buffer is excluded

### ISSUE THREAD

**Issue by lazywei** [danielfalk/smart-open.nvim#10]
Not sure if this is intended but it seems the file opened in the current buffer is excluded from the search result. While I understand the reason of doing so I'm still wondering if there is a way to toggle such behavior? I would like to just using the same keystroke to open any file at any time.

Thanks

**Comment by danielfalk** [comment]
It's intentional.  The idea is for this to require as few keystrokes as possible and give you the most relevant results possible, so including the file you're already in is unnecessary clutter and possibly confusing. 

That's the thought anyway.  I'd like to keep this open for the time being and continue the discussion for any who are interested to have it.  I'd be interested in figuring out a way of getting at what your asking for without any real drawbacks if there's a way.

Any reason you'd want to open the same file you're already in?

**Comment by danielfalk** [comment]
So you don't really think about what file you're in, but you reflexively pop it open and want to switch files.  So I assume you're typing in a search term then?

I'm wondering if it would make sense to allow the current file, but make it a special case where it doesn't score very high (therefore requiring a closer match to your search for it to surface).  Would that work?  I'd rather not introduce an option for it, because for something like this it should either be workable or not.  

The line you cite looks correct, but I don't know what downstream implications that's going to have to the weights and the automatic adjustments.  (It might work for your purposes, but I'm more interested in the broader usage.)

**Comment by danielfalk** [comment]
This change is on the `0.2.x` branch.  If you're interested in providing feedback, the branch is pushed.  I tried to create an indicator that the file is the current buffer, and so far have settled on using the "Comment" syntax highlighting class.  I'm not sure if this is the best approach and am open to feedback on that.  Still I think it's useful to see some sort of cue that you're actually going back to the file you were just in.

**Comment by danielfalk** [comment]
Implemented on 0.2.x branch
