### ISSUE TITLE
When no input, show recent files first

### ISSUE THREAD

**Issue by titouancreach** [danielfalk/smart-open.nvim#26]
Hello
I believe that when we open a project, and just open :Telescope smart_open, the most "interesting" / "smart" choice we can have is the recent file rather than the files with the high score. But I understand it's a matter of opinion. (I think this is what vscode is doing) :)

**Comment by danielfalk** [comment]
Hey thanks for leaving feedback, and thanks for your previous PR also!

Yeah, you could say that smart-open bases its choice upon the "high score", but this score takes into account recency!  It also happens to take other factors into account as well as noted in the docs, but if you find that recent files are **always** the files you are liable to choose, then that's OK too, because smart-open will adapt!  Over time as you choose the files that are recent, smart-open boosts the recency factor to the point that you, in effect, get the behavior you're looking for.

As a side note, I found that for my usage, recency is only one of the things that correlated to the actual file I was wanting to go to.  Just as an example, some files I use quite frequently but after jumping around in different files for a while, they no longer came up or were way down in the list.

I totally understand there are personal preferences here, so I designed this to learn from you and your usage.  If it's not learning well enough or fast enough, we could make some adjustments, but that's the idea anyway.

P.S., I just enabled github's "discussions" feature, which might be better for feedback on the design.  So I'm closing this issue for now, but you have additional ideas, maybe we could workshop something in the discussions?  Thanks again.
