### ISSUE TITLE
space after filename is not working (should search for folder instead filename)

### ISSUE THREAD

**Issue by otavioschwanck** [danielfalk/smart-open.nvim#45]
if i search only the file works:

![image](https://github.com/danielfalk/smart-open.nvim/assets/9551316/66d13fd2-fd36-4a16-bbeb-24e9ef525622)

if i search the path afterwards, doesn't works:

![image](https://github.com/danielfalk/smart-open.nvim/assets/9551316/e9409c22-7182-4301-a2b9-644e6731e597)

Tried with fzf and fzy and filename_first is `true`.

-- 

With filename_first false works only using `/`:

![image](https://github.com/danielfalk/smart-open.nvim/assets/9551316/83df557b-3a70-4ea2-8afc-4a9bd919c69c)

If i try to use space, doesn't work (i prefer space 100000x times):
![image](https://github.com/danielfalk/smart-open.nvim/assets/9551316/ddf07bd1-bfcf-49fe-956c-08917f7c8ad6)

Would be awesome to have a option to use `space` as separator instead / for filename_first `false`.

Is possible to do it?

**Comment by otavioschwanck** [comment]
After the PR:

![image](https://github.com/danielfalk/smart-open.nvim/assets/9551316/36231a25-4c1f-4697-96b2-a8e6c8411475)

![image](https://github.com/danielfalk/smart-open.nvim/assets/9551316/f9c95de7-cd59-4880-bdb4-b144887f6338)

**Comment by danielfalk** [comment]
How it's displayed is different from how it's searched.  For searching, that's delegated to fzy or fzf, depending on your configuration, and the search algorithm is given the full path (i.e., /path/to/my/file_name.foo) to match on.

Your issue here has just made me realize that this is a bit counter-intuitive, but I still think it's the right way to do it overall.

I'm surprised `mo kyc` doesn't work with fzf.  That seems to work for me.  Could you have been trying that search with fzy?

**Comment by danielfalk** [comment]
Never got a response on this, so closing for now.  If there's still an issue, feel free to clarify and reopen
