### ISSUE TITLE
add ability to only search history

### ISSUE THREAD

**Issue by rr0gi** [danielfalk/smart-open.nvim#54]
arguably it makes the plugin less "smart" but if cwd_only exists then history_only can also exist :)

**Comment by danielfalk** [comment]
`cwd_only` exists because it solves a frequent problem, where users are working in a sort of "project mode" and the "smartness" isn't enough to fully remove all the irrelevant entries.

If this solves a similar problem that I'm not seeing. we can revisit, but otherwise, the generally philosophy is to resist the temptation to add more config.  The short reason is because it's yet more documentation, more complexity, and more configuration permutations that all need to be tested.

I'd suggest the builtin `:Telescope oldfiles` functionality if all you want to do is search history.
