### ISSUE TITLE
In newly-visited projects, not all files are findable

### ISSUE THREAD

**Issue by NullVoxPopuli** [danielfalk/smart-open.nvim#9]
I noticed this the most with ci.yml (GitHub Action file), as I hope around between projects.

My smart-open command is: 
```vim
nnoremap <C-t> :lua require('telescope').extensions.smart_open.smart_open({cwd_only = true})<CR>
```

maybe there is some default filter I need to configure?

**Comment by danielfalk** [comment]
It wasn't including hidden files by default when scanning.  I've pushed a fix.  Note that this might create annoying side-effects if you run neovim with your home directory as the current working directory, since that directory tends to have a lot of hidden files cluttering it.

I'm not sure what the right answer for that is, but one _could_ work around that by creating a `~/.ff-ignore` and adding patterns in it.

**Comment by ilan-schemoul** [comment]
.gitignore makes everything extremely slow and he's breaking expectations as Telescope normally ignores everything in .gitignore. It doesn't make a UX (I've used this package for months without knowing it doesn't respect .gitignore).
I made a PR to streamline this plugin behaviour with the rest of Telescope https://github.com/danielfalk/smart-open.nvim/pull/80
.gitignore should be respect by default but it becomes configurable
